// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// scimesh_render_mesh
List scimesh_render_mesh(List mesh_data, List camera_data, List options_data);
RcppExport SEXP _scimesh_scimesh_render_mesh(SEXP mesh_dataSEXP, SEXP camera_dataSEXP, SEXP options_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mesh_data(mesh_dataSEXP);
    Rcpp::traits::input_parameter< List >::type camera_data(camera_dataSEXP);
    Rcpp::traits::input_parameter< List >::type options_data(options_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_render_mesh(mesh_data, camera_data, options_data));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_render_scene
List scimesh_render_scene(List scene_data, List camera_data, List options_data);
RcppExport SEXP _scimesh_scimesh_render_scene(SEXP scene_dataSEXP, SEXP camera_dataSEXP, SEXP options_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type scene_data(scene_dataSEXP);
    Rcpp::traits::input_parameter< List >::type camera_data(camera_dataSEXP);
    Rcpp::traits::input_parameter< List >::type options_data(options_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_render_scene(scene_data, camera_data, options_data));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_camera_fit_mesh
List scimesh_camera_fit_mesh(List mesh_data, NumericVector direction, NumericVector up, double fov_degrees, double margin);
RcppExport SEXP _scimesh_scimesh_camera_fit_mesh(SEXP mesh_dataSEXP, SEXP directionSEXP, SEXP upSEXP, SEXP fov_degreesSEXP, SEXP marginSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mesh_data(mesh_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type direction(directionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type up(upSEXP);
    Rcpp::traits::input_parameter< double >::type fov_degrees(fov_degreesSEXP);
    Rcpp::traits::input_parameter< double >::type margin(marginSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_camera_fit_mesh(mesh_data, direction, up, fov_degrees, margin));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scimesh_scimesh_render_mesh", (DL_FUNC) &_scimesh_scimesh_render_mesh, 3},
    {"_scimesh_scimesh_render_scene", (DL_FUNC) &_scimesh_scimesh_render_scene, 3},
    {"_scimesh_scimesh_camera_fit_mesh", (DL_FUNC) &_scimesh_scimesh_camera_fit_mesh, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_scimesh(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
