// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// scimesh_render_mesh
List scimesh_render_mesh(List mesh_data, List camera_data, List options_data);
RcppExport SEXP _scimesh_scimesh_render_mesh(SEXP mesh_dataSEXP, SEXP camera_dataSEXP, SEXP options_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mesh_data(mesh_dataSEXP);
    Rcpp::traits::input_parameter< List >::type camera_data(camera_dataSEXP);
    Rcpp::traits::input_parameter< List >::type options_data(options_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_render_mesh(mesh_data, camera_data, options_data));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_render_scene
List scimesh_render_scene(List scene_data, List camera_data, List options_data);
RcppExport SEXP _scimesh_scimesh_render_scene(SEXP scene_dataSEXP, SEXP camera_dataSEXP, SEXP options_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type scene_data(scene_dataSEXP);
    Rcpp::traits::input_parameter< List >::type camera_data(camera_dataSEXP);
    Rcpp::traits::input_parameter< List >::type options_data(options_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_render_scene(scene_data, camera_data, options_data));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_camera_fit_mesh
List scimesh_camera_fit_mesh(List mesh_data, NumericVector direction, NumericVector up, double fov_degrees, double margin);
RcppExport SEXP _scimesh_scimesh_camera_fit_mesh(SEXP mesh_dataSEXP, SEXP directionSEXP, SEXP upSEXP, SEXP fov_degreesSEXP, SEXP marginSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mesh_data(mesh_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type direction(directionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type up(upSEXP);
    Rcpp::traits::input_parameter< double >::type fov_degrees(fov_degreesSEXP);
    Rcpp::traits::input_parameter< double >::type margin(marginSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_camera_fit_mesh(mesh_data, direction, up, fov_degrees, margin));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_transform_mesh
List scimesh_transform_mesh(List mesh_data, NumericMatrix matrix_4x4);
RcppExport SEXP _scimesh_scimesh_transform_mesh(SEXP mesh_dataSEXP, SEXP matrix_4x4SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mesh_data(mesh_dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type matrix_4x4(matrix_4x4SEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_transform_mesh(mesh_data, matrix_4x4));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_translate_mesh
List scimesh_translate_mesh(List mesh_data, NumericVector translation);
RcppExport SEXP _scimesh_scimesh_translate_mesh(SEXP mesh_dataSEXP, SEXP translationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mesh_data(mesh_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type translation(translationSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_translate_mesh(mesh_data, translation));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_scale_mesh
List scimesh_scale_mesh(List mesh_data, double scale);
RcppExport SEXP _scimesh_scimesh_scale_mesh(SEXP mesh_dataSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mesh_data(mesh_dataSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_scale_mesh(mesh_data, scale));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_rotate_mesh
List scimesh_rotate_mesh(List mesh_data, double angle_rad, NumericVector axis);
RcppExport SEXP _scimesh_scimesh_rotate_mesh(SEXP mesh_dataSEXP, SEXP angle_radSEXP, SEXP axisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mesh_data(mesh_dataSEXP);
    Rcpp::traits::input_parameter< double >::type angle_rad(angle_radSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type axis(axisSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_rotate_mesh(mesh_data, angle_rad, axis));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_generate_multi_spheres
List scimesh_generate_multi_spheres(NumericMatrix centers, NumericVector radii, NumericMatrix colors, int segments);
RcppExport SEXP _scimesh_scimesh_generate_multi_spheres(SEXP centersSEXP, SEXP radiiSEXP, SEXP colorsSEXP, SEXP segmentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type radii(radiiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type colors(colorsSEXP);
    Rcpp::traits::input_parameter< int >::type segments(segmentsSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_generate_multi_spheres(centers, radii, colors, segments));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_generate_multi_cylinders
List scimesh_generate_multi_cylinders(NumericMatrix starts, NumericMatrix ends, NumericVector radii, NumericMatrix colors, int segments);
RcppExport SEXP _scimesh_scimesh_generate_multi_cylinders(SEXP startsSEXP, SEXP endsSEXP, SEXP radiiSEXP, SEXP colorsSEXP, SEXP segmentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ends(endsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type radii(radiiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type colors(colorsSEXP);
    Rcpp::traits::input_parameter< int >::type segments(segmentsSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_generate_multi_cylinders(starts, ends, radii, colors, segments));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_generate_cone
List scimesh_generate_cone(NumericVector base, NumericVector tip, double radius, int segments, NumericVector color);
RcppExport SEXP _scimesh_scimesh_generate_cone(SEXP baseSEXP, SEXP tipSEXP, SEXP radiusSEXP, SEXP segmentsSEXP, SEXP colorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type base(baseSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tip(tipSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< int >::type segments(segmentsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type color(colorSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_generate_cone(base, tip, radius, segments, color));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_render_triangles_raw
List scimesh_render_triangles_raw(NumericMatrix positions, NumericMatrix colors, List camera_data, List options_data);
RcppExport SEXP _scimesh_scimesh_render_triangles_raw(SEXP positionsSEXP, SEXP colorsSEXP, SEXP camera_dataSEXP, SEXP options_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type positions(positionsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type colors(colorsSEXP);
    Rcpp::traits::input_parameter< List >::type camera_data(camera_dataSEXP);
    Rcpp::traits::input_parameter< List >::type options_data(options_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_render_triangles_raw(positions, colors, camera_data, options_data));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_render_points_raw
List scimesh_render_points_raw(NumericMatrix positions, NumericMatrix colors, double radius, List camera_data, List options_data);
RcppExport SEXP _scimesh_scimesh_render_points_raw(SEXP positionsSEXP, SEXP colorsSEXP, SEXP radiusSEXP, SEXP camera_dataSEXP, SEXP options_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type positions(positionsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type colors(colorsSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< List >::type camera_data(camera_dataSEXP);
    Rcpp::traits::input_parameter< List >::type options_data(options_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_render_points_raw(positions, colors, radius, camera_data, options_data));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_generate_cuboid
List scimesh_generate_cuboid(NumericVector center, NumericVector half_extents, NumericVector color);
RcppExport SEXP _scimesh_scimesh_generate_cuboid(SEXP centerSEXP, SEXP half_extentsSEXP, SEXP colorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type center(centerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type half_extents(half_extentsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type color(colorSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_generate_cuboid(center, half_extents, color));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_generate_pyramid
List scimesh_generate_pyramid(NumericVector base_center, NumericVector apex, double half_width, NumericVector color);
RcppExport SEXP _scimesh_scimesh_generate_pyramid(SEXP base_centerSEXP, SEXP apexSEXP, SEXP half_widthSEXP, SEXP colorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type base_center(base_centerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type apex(apexSEXP);
    Rcpp::traits::input_parameter< double >::type half_width(half_widthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type color(colorSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_generate_pyramid(base_center, apex, half_width, color));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_generate_tetrahedron
List scimesh_generate_tetrahedron(NumericVector p0, NumericVector p1, NumericVector p2, NumericVector p3, NumericVector color);
RcppExport SEXP _scimesh_scimesh_generate_tetrahedron(SEXP p0SEXP, SEXP p1SEXP, SEXP p2SEXP, SEXP p3SEXP, SEXP colorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p3(p3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type color(colorSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_generate_tetrahedron(p0, p1, p2, p3, color));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_generate_torus
List scimesh_generate_torus(NumericVector center, double major_radius, double minor_radius, int major_segments, int minor_segments, NumericVector color);
RcppExport SEXP _scimesh_scimesh_generate_torus(SEXP centerSEXP, SEXP major_radiusSEXP, SEXP minor_radiusSEXP, SEXP major_segmentsSEXP, SEXP minor_segmentsSEXP, SEXP colorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type center(centerSEXP);
    Rcpp::traits::input_parameter< double >::type major_radius(major_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type minor_radius(minor_radiusSEXP);
    Rcpp::traits::input_parameter< int >::type major_segments(major_segmentsSEXP);
    Rcpp::traits::input_parameter< int >::type minor_segments(minor_segmentsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type color(colorSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_generate_torus(center, major_radius, minor_radius, major_segments, minor_segments, color));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_generate_plane
List scimesh_generate_plane(NumericVector center, NumericVector normal, double half_size_x, double half_size_y, NumericVector color);
RcppExport SEXP _scimesh_scimesh_generate_plane(SEXP centerSEXP, SEXP normalSEXP, SEXP half_size_xSEXP, SEXP half_size_ySEXP, SEXP colorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type center(centerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type normal(normalSEXP);
    Rcpp::traits::input_parameter< double >::type half_size_x(half_size_xSEXP);
    Rcpp::traits::input_parameter< double >::type half_size_y(half_size_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type color(colorSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_generate_plane(center, normal, half_size_x, half_size_y, color));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_read_stl
List scimesh_read_stl(CharacterVector path);
RcppExport SEXP _scimesh_scimesh_read_stl(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_read_stl(path));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_write_stl
void scimesh_write_stl(List mesh_data, CharacterVector path, String format);
RcppExport SEXP _scimesh_scimesh_write_stl(SEXP mesh_dataSEXP, SEXP pathSEXP, SEXP formatSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mesh_data(mesh_dataSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type path(pathSEXP);
    Rcpp::traits::input_parameter< String >::type format(formatSEXP);
    scimesh_write_stl(mesh_data, path, format);
    return R_NilValue;
END_RCPP
}
// scimesh_read_obj
List scimesh_read_obj(CharacterVector path);
RcppExport SEXP _scimesh_scimesh_read_obj(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_read_obj(path));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_read_ply
List scimesh_read_ply(CharacterVector path);
RcppExport SEXP _scimesh_scimesh_read_ply(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_read_ply(path));
    return rcpp_result_gen;
END_RCPP
}
// scimesh_write_png
bool scimesh_write_png(List image, CharacterVector filename);
RcppExport SEXP _scimesh_scimesh_write_png(SEXP imageSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type image(imageSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(scimesh_write_png(image, filename));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scimesh_scimesh_render_mesh", (DL_FUNC) &_scimesh_scimesh_render_mesh, 3},
    {"_scimesh_scimesh_render_scene", (DL_FUNC) &_scimesh_scimesh_render_scene, 3},
    {"_scimesh_scimesh_camera_fit_mesh", (DL_FUNC) &_scimesh_scimesh_camera_fit_mesh, 5},
    {"_scimesh_scimesh_transform_mesh", (DL_FUNC) &_scimesh_scimesh_transform_mesh, 2},
    {"_scimesh_scimesh_translate_mesh", (DL_FUNC) &_scimesh_scimesh_translate_mesh, 2},
    {"_scimesh_scimesh_scale_mesh", (DL_FUNC) &_scimesh_scimesh_scale_mesh, 2},
    {"_scimesh_scimesh_rotate_mesh", (DL_FUNC) &_scimesh_scimesh_rotate_mesh, 3},
    {"_scimesh_scimesh_generate_multi_spheres", (DL_FUNC) &_scimesh_scimesh_generate_multi_spheres, 4},
    {"_scimesh_scimesh_generate_multi_cylinders", (DL_FUNC) &_scimesh_scimesh_generate_multi_cylinders, 5},
    {"_scimesh_scimesh_generate_cone", (DL_FUNC) &_scimesh_scimesh_generate_cone, 5},
    {"_scimesh_scimesh_render_triangles_raw", (DL_FUNC) &_scimesh_scimesh_render_triangles_raw, 4},
    {"_scimesh_scimesh_render_points_raw", (DL_FUNC) &_scimesh_scimesh_render_points_raw, 5},
    {"_scimesh_scimesh_generate_cuboid", (DL_FUNC) &_scimesh_scimesh_generate_cuboid, 3},
    {"_scimesh_scimesh_generate_pyramid", (DL_FUNC) &_scimesh_scimesh_generate_pyramid, 4},
    {"_scimesh_scimesh_generate_tetrahedron", (DL_FUNC) &_scimesh_scimesh_generate_tetrahedron, 5},
    {"_scimesh_scimesh_generate_torus", (DL_FUNC) &_scimesh_scimesh_generate_torus, 6},
    {"_scimesh_scimesh_generate_plane", (DL_FUNC) &_scimesh_scimesh_generate_plane, 5},
    {"_scimesh_scimesh_read_stl", (DL_FUNC) &_scimesh_scimesh_read_stl, 1},
    {"_scimesh_scimesh_write_stl", (DL_FUNC) &_scimesh_scimesh_write_stl, 3},
    {"_scimesh_scimesh_read_obj", (DL_FUNC) &_scimesh_scimesh_read_obj, 1},
    {"_scimesh_scimesh_read_ply", (DL_FUNC) &_scimesh_scimesh_read_ply, 1},
    {"_scimesh_scimesh_write_png", (DL_FUNC) &_scimesh_scimesh_write_png, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_scimesh(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
