# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scimesh_render_mesh <- function(mesh_data, camera_data, options_data) {
    .Call(`_scimesh_scimesh_render_mesh`, mesh_data, camera_data, options_data)
}

scimesh_render_scene <- function(scene_data, camera_data, options_data) {
    .Call(`_scimesh_scimesh_render_scene`, scene_data, camera_data, options_data)
}

scimesh_camera_fit_mesh <- function(mesh_data, direction, up, fov_degrees = 45.0, margin = 1.1, projection = "perspective") {
    .Call(`_scimesh_scimesh_camera_fit_mesh`, mesh_data, direction, up, fov_degrees, margin, projection)
}

scimesh_transform_mesh <- function(mesh_data, matrix_4x4) {
    .Call(`_scimesh_scimesh_transform_mesh`, mesh_data, matrix_4x4)
}

scimesh_translate_mesh <- function(mesh_data, translation) {
    .Call(`_scimesh_scimesh_translate_mesh`, mesh_data, translation)
}

scimesh_scale_mesh <- function(mesh_data, scale) {
    .Call(`_scimesh_scimesh_scale_mesh`, mesh_data, scale)
}

scimesh_scale_mesh_nonuniform <- function(mesh_data, scale) {
    .Call(`_scimesh_scimesh_scale_mesh_nonuniform`, mesh_data, scale)
}

scimesh_rotate_mesh <- function(mesh_data, angle_rad, axis) {
    .Call(`_scimesh_scimesh_rotate_mesh`, mesh_data, angle_rad, axis)
}

scimesh_generate_multi_spheres <- function(centers, radii, colors, segments = 16L) {
    .Call(`_scimesh_scimesh_generate_multi_spheres`, centers, radii, colors, segments)
}

scimesh_generate_multi_cylinders <- function(starts, ends, radii, colors, segments = 12L) {
    .Call(`_scimesh_scimesh_generate_multi_cylinders`, starts, ends, radii, colors, segments)
}

scimesh_generate_cone <- function(base, tip, radius, segments, color) {
    .Call(`_scimesh_scimesh_generate_cone`, base, tip, radius, segments, color)
}

scimesh_generate_arrow <- function(from, to, shaft_radius, head_radius, head_length, segments, color) {
    .Call(`_scimesh_scimesh_generate_arrow`, from, to, shaft_radius, head_radius, head_length, segments, color)
}

scimesh_render_triangles_raw <- function(positions, colors, camera_data, options_data) {
    .Call(`_scimesh_scimesh_render_triangles_raw`, positions, colors, camera_data, options_data)
}

scimesh_render_points_raw <- function(positions, colors, radius, camera_data, options_data) {
    .Call(`_scimesh_scimesh_render_points_raw`, positions, colors, radius, camera_data, options_data)
}

scimesh_generate_cuboid <- function(center, half_extents, color) {
    .Call(`_scimesh_scimesh_generate_cuboid`, center, half_extents, color)
}

scimesh_generate_pyramid <- function(base_center, apex, half_width, color) {
    .Call(`_scimesh_scimesh_generate_pyramid`, base_center, apex, half_width, color)
}

scimesh_generate_tetrahedron <- function(p0, p1, p2, p3, color) {
    .Call(`_scimesh_scimesh_generate_tetrahedron`, p0, p1, p2, p3, color)
}

scimesh_generate_torus <- function(center, major_radius, minor_radius, major_segments, minor_segments, color) {
    .Call(`_scimesh_scimesh_generate_torus`, center, major_radius, minor_radius, major_segments, minor_segments, color)
}

scimesh_generate_plane <- function(center, normal, half_size_x, half_size_y, color) {
    .Call(`_scimesh_scimesh_generate_plane`, center, normal, half_size_x, half_size_y, color)
}

scimesh_read_stl <- function(path) {
    .Call(`_scimesh_scimesh_read_stl`, path)
}

scimesh_write_stl <- function(mesh_data, path, format = "binary") {
    invisible(.Call(`_scimesh_scimesh_write_stl`, mesh_data, path, format))
}

scimesh_read_obj <- function(path) {
    .Call(`_scimesh_scimesh_read_obj`, path)
}

scimesh_read_ply <- function(path) {
    .Call(`_scimesh_scimesh_read_ply`, path)
}

scimesh_write_png <- function(image, filename) {
    .Call(`_scimesh_scimesh_write_png`, image, filename)
}

scimesh_image_crop <- function(image, x, y, w, h) {
    .Call(`_scimesh_scimesh_image_crop`, image, x, y, w, h)
}

scimesh_image_merge <- function(image, other, direction) {
    .Call(`_scimesh_scimesh_image_merge`, image, other, direction)
}

scimesh_image_grow <- function(image, top, bottom, left, right, background) {
    .Call(`_scimesh_scimesh_image_grow`, image, top, bottom, left, right, background)
}

scimesh_image_rotate_90 <- function(image, clockwise) {
    .Call(`_scimesh_scimesh_image_rotate_90`, image, clockwise)
}

scimesh_image_scale <- function(image, new_width, new_height) {
    .Call(`_scimesh_scimesh_image_scale`, image, new_width, new_height)
}

scimesh_image_crop_to_content <- function(image, direction, background) {
    .Call(`_scimesh_scimesh_image_crop_to_content`, image, direction, background)
}

scimesh_compute_vertex_normals <- function(mesh_data) {
    .Call(`_scimesh_scimesh_compute_vertex_normals`, mesh_data)
}

