# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scimesh_render_mesh <- function(mesh_data, camera_data, options_data) {
    .Call(`_scimesh_scimesh_render_mesh`, mesh_data, camera_data, options_data)
}

scimesh_render_scene <- function(scene_data, camera_data, options_data) {
    .Call(`_scimesh_scimesh_render_scene`, scene_data, camera_data, options_data)
}

scimesh_camera_fit_mesh <- function(mesh_data, direction, up, fov_degrees = 45.0, margin = 1.1) {
    .Call(`_scimesh_scimesh_camera_fit_mesh`, mesh_data, direction, up, fov_degrees, margin)
}

scimesh_transform_mesh <- function(mesh_data, matrix_4x4) {
    .Call(`_scimesh_scimesh_transform_mesh`, mesh_data, matrix_4x4)
}

scimesh_translate_mesh <- function(mesh_data, translation) {
    .Call(`_scimesh_scimesh_translate_mesh`, mesh_data, translation)
}

scimesh_scale_mesh <- function(mesh_data, scale) {
    .Call(`_scimesh_scimesh_scale_mesh`, mesh_data, scale)
}

scimesh_rotate_mesh <- function(mesh_data, angle_rad, axis) {
    .Call(`_scimesh_scimesh_rotate_mesh`, mesh_data, angle_rad, axis)
}

scimesh_generate_multi_spheres <- function(centers, radii, colors, segments = 16L) {
    .Call(`_scimesh_scimesh_generate_multi_spheres`, centers, radii, colors, segments)
}

scimesh_generate_multi_cylinders <- function(starts, ends, radii, colors, segments = 12L) {
    .Call(`_scimesh_scimesh_generate_multi_cylinders`, starts, ends, radii, colors, segments)
}

