# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scimesh_render_mesh <- function(mesh_data, camera_data, options_data) {
    .Call(`_scimesh_scimesh_render_mesh`, mesh_data, camera_data, options_data)
}

scimesh_render_scene <- function(scene_data, camera_data, options_data) {
    .Call(`_scimesh_scimesh_render_scene`, scene_data, camera_data, options_data)
}

scimesh_camera_fit_mesh <- function(mesh_data, direction, up, fov_degrees = 45.0, margin = 1.1) {
    .Call(`_scimesh_scimesh_camera_fit_mesh`, mesh_data, direction, up, fov_degrees, margin)
}

